### PR TITLE
Use ACE arsenal actions instead of UI button

### PR DESCRIPTION
**Pull request by johnb432**
**When merged this pull request will:**
- Title.
- Fixed indentations in `stringtable.xml`

### CODE REVIEW

**Comment by johnb432** [comment]
Something weird happens when you press the text in the arsenal - needs investigating, so don't merge quite yet.

**Comment by johnb432** [comment]
You can go ahead and merge it if you want, it's a bug in ACE.

**Comment by johnb432** [comment]
@mjc4wilton What's the status with this PR? Does something need to be done on my end?

**Review by LinkIsGrim — APPROVED** [review]
I've been using this for a while in my community and it works as expected.

**Pull request merged**
