### PR TITLE
Hemtt 191

### PR DESCRIPTION
**Pull request by ampersand38**
**When merged this pull request will:**
- Update mod structure for hemtt 1.9.1
- VS Code Run Build Task Ctrl+Shift+B
- Fix mod info inconsistencies

### CODE REVIEW

**Comment by mjc4wilton** [comment]
You added .hemtt to the gitignore, which is where the project file configuration is, so this does not build currently

**Comment by mjc4wilton** [comment]
Thanks for doing a lot of the work on this. Already converted 3 of my other repos over to hemtt 1.0 so saving some work here is nice. Will merge tomorrow probably after I give it another look, but CI seems to be working now.

**Comment by ampersand38** [comment]
You're welcome! Excited for the coming update =)

**Comment by johnb432** [comment]
@mjc4wilton Are you going to merge this? I want to start working on better integration with the ACE arsenal and having this feature pushed to the main branch would make it easier.

**Comment by mjc4wilton** [comment]
Nope. Not gonna merge. Totally didn't get busy and forget about this.

**Pull request merged**
